### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by Vicent9920** [imyyq-star/MVVMArchitectureSample#1]
按照README文件依赖后，依然无法运行，是什么情况啊？没有报错，只是找不到app模块

**Comment by imyyq-star** [comment]
找到 app 模块是什么意思？此项目没有 app 模块的，只有 sample 和 sample-java 这两个，更新下项目代码，同时也更新下 MVVMArchitecture 子仓库的代码。

**Comment by Vicent9920** [comment]
sample-java也没有啊

**Comment by imyyq-star** [comment]
感觉你说的是 MVVMArchitecture 框架。
这个项目是 MVVMArchitecture 的 Sample 例子项目，MVVMArchitecture 才是框架源码，是一个 Android Module，详细可见  [MVVMArchitecture Wiki](https://github.com/imyyq-star/MVVMArchitecture/wiki/1%E3%80%81%E5%BC%95%E5%85%A5%E6%A1%86%E6%9E%B6)

**Comment by Vicent9920** [comment]
总之，就是跑不起来。。。。。
下载这个项目，然后依赖MVVMArchitecture，然后运行不起来。。。。。。

**Comment by imyyq-star** [comment]
可以截个运行不起来的项目目录图。或者加 q 群 828441270 沟通比较快
框架需要对 git 和 AS 的项目结构有一定的了解才能融会贯通
